--- 

- name: "create user"
  user: 
    createhome: true
    home: "{{ nas_path }} / {{ user_id }} "
    name: "{{ user_id }}"
    shell: /bin/bash
    state: present
    
- name: Add user to docker
  user: 
    name: "{{ user_id }}"
    shell: /bin/bash
    state: present
    group: docker
    when: 
      -  "{{ docker_access is true }}"
      
        
- name: "Add linux ID to slurm cluster"
  when: "'slurmcontroller' in group_names "
  command: "sacctmgr create user name=< {{ user_id }} > cluster=cluster qos=< {{ user_qos_input }} >"
