---
- name: Create Users 
  hosts: all
  tasks:
- name: create user  
  user:
    name: "{{ user_id }}"
    state: present
    shell: /bin/bash
    createhome: yes
    home: "{{ nas_path }}" 

- name: Add user to docker  
      user:
        name: "{{ user_id }}"
        state: present
        when: 
         - "{{ docker_access is true }}" 
         - "'slurmexechosts' in group_names or 'exec' in slurm_roles"
         - "'slurmservers' in group_names or 'controller' in slurm_roles"
           
- name: Add linux ID to slurm cluster
  command: sacctmgr create user name=<provided_linux_id> cluster=cluster qos=<user_qos_input> 
  when: "'slurmservers' in group_names or 'controller' in slurm_roles"
