--- 

- name: "create user"
  user: 
    createhome: true
    home: "{{ nas_path }} / {{ user_id }} "
    name: "{{ user_id }}"
    shell: /bin/bash
    state: present
    
- name: Add user to docker
  ansible.builtin.user: 
    name: "{{ user_id }}"
    shell: /bin/bash
    state: present
    when: 
      - "'slurmcompute01' in group_names "
      - "'slurmcontroller' in group_names "
      
      
- name: "Add linux ID to slurm cluster"
  when: "'slurmcontroller' in group_names "
  command: "sacctmgr create user name=< {{ user_id }} > cluster=cluster qos=< {{ user_qos_input }} >"
